# Generated by Django 5.2.6 on 2025-09-29 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +233XXXXXXXXX or 0XXXXXXXXX', regex='^(\\+233|0)[0-9]{9}$')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('ghana_card_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ghana Card number must be in format: GHA-XXXXXXXXX-X', regex='^GHA-[0-9]{9}-[0-9]$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(help_text='Unique teacher identifier (e.g., TEACH001)', max_length=20, unique=True)),
                ('hire_date', models.DateField()),
                ('specialization', models.CharField(help_text='Primary subject/area of expertise', max_length=100)),
                ('qualification', models.CharField(choices=[('diploma', 'Diploma in Education'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], default='degree', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['employee_id'], name='teachers_te_employe_8033d0_idx'), models.Index(fields=['is_active'], name='teachers_te_is_acti_964ac2_idx')],
            },
        ),
    ]
