# Generated by Django 5.2.6 on 2025-10-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='teachers_te_employe_8033d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='teachers_te_is_acti_964ac2_idx',
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_status',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/profiles/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(help_text='Subject or area of specialization', max_length=100),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers_teacher',
        ),
    ]
